all:
	clang++ --std=c++14 -Weverything -Wno-c++98-compat -Wno-missing-prototypes -fno-elide-constructors -o naive naive.cpp
	clang++ --std=c++14 -Weverything -Wno-c++98-compat -Wno-missing-prototypes -fno-elide-constructors -o expTmplt expTmplt.cpp
